version: "3"
services:
  pptp:
    env_file: .env
    build: .    
    network_mode: host    
    devices:
      - /dev/ppp:/dev/ppp
    privileged: true    
    command: pptp ${VPN_HOST} ${VPN_USER}
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
